name: Change Detection

on:
  repository_dispatch:
    types:
      - jira_issue_transition

jobs:
  process-jira-event:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: List Branches and Set Outputs
        id: list-branches
        run: |
          git fetch --all --prune
          git branch -a
          branches=$(git branch -a)
          if echo "${branches}" | grep -q "${{ github.event.client_payload.issueKey }}"; then
            echo "${{ github.event.client_payload.issueKey }} branch exists."
            echo "TARGET_BRANCH=exists" >> $GITHUB_ENV
          else
            echo "Branch ${{ github.event.client_payload.issueKey }} does not exist. Skipping subsequent steps."
            echo "TARGET_BRANCH=not_exists" >> $GITHUB_ENV
            exit 0
          fi

      - name: Update JIRA Custom Fields
        run: |
          # Extract issueKey from the payload
          issueKey=${{ github.event.client_payload.issueKey }}
          # Your JIRA API URL
          jiraUrl="https://testjiragitautomation.atlassian.net/rest/api/3/issue/${issueKey}"
          # Your JIRA Custom Field IDs
          customFieldIdAPI="customfield_10040"
          customFieldIdSchema="customfield_10041"
          # JIRA username (email)
          jiraUsername="muhammadshoaibajk@gmail.com"
          # JIRA API token or password
          jiraToken=${{ secrets.JIRA_API_TOKEN_ORGANIZATION }}
          # Update custom field for API change
            curl -X PUT \
              -H "Content-Type: application/json" \
              -u "${jiraUsername}:${jiraToken}" \
              -d '{
                "fields": {
                  "customfield_10040": "fuck"
                }
              }' \
              "${jiraUrl}"
          
