name: Comment on Jira Ticket
on:
  push:
    branches:
      - main

jobs:
  comment_on_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comment on Jira Ticket
        env:
          ORGANIZATION_SECRET: ${{ secrets.ORGANIZATION_SECRET }}
        run: |
          curl -D- -u shoaib40ce@gmail.com:${ORGANIZATION_SECRET} -X POST -H "Content-Type: application/json" \
          https://gittest.atlassian.net/rest/api/3/issue/TEST-2/comment -d '{
            "body": "This is a test comment added via GitHub Action."
          }'
